name: CI
on:
    push:
        branches: [ master ]
    
jobs:
    deploy:
        runs-on: self-hosted
    
    strategy: 
        matrix:
            node-version: [18.16.0]
   steps:
      - run: npm install
      #- uses: actions/checkout@v2
      #- name: Use Node.js ${{ matrix.node-version }}
       # uses: actions/setup-node@v1
        #with:
         #   node-version: ${{ matrix.node-version }}
    #  - run: npm run build --if-present
     # - run: npm test

    #- https://medium.com/@g.c.dassanayake/deploying-a-nodejs-application-using-github-actions-e5f4bde7b21b